In [1]:
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import pandas_profiling

/tmp/ipykernel_28222/4274494042.py:4: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  import pandas_profiling

In [2]:
udemy=pd.read_csv('udemy_courses.csv')
edx=pd.read_csv('edx_courses.csv')
coursera=pd.read_csv('Coursera_courses.csv')
courseraReviews=pd.read_csv('Coursera_reviews.csv')

Para poder entender bien los datos, vamos a ver el head de cada dataset y a estudiar los dtypes tambi√©n

In [3]:
udemy.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

In [4]:
udemy.dtypes

course_id                int64
course_title            object
url                     object
is_paid                   bool
price                    int64
num_subscribers          int64
num_reviews              int64
num_lectures             int64
level                   object
content_duration       float64
published_timestamp     object
subject                 object
dtype: object

In [5]:
edx.head()

,title,summary,n_enrolled,course_type,institution,instructors,Level,subject,language,subtitles,course_effort,course_length,price,course_description,course_syllabus,course_url
0,How to Learn Online,Learn essential strategies for successful onli...,"124,980",Self-paced on your time,edX,Nina Huntemann-Robyn Belair-Ben Piscopo,Introductory,Education & Teacher Training,English,English,2‚Äì3 hours per week,2 Weeks,FREE-Add a Verified Certificate for $49 USD,"Designed for those who are new to elearning, t...",Welcome - We start with opportunities to meet ...,https://www.edx.org/course/how-to-learn-online
1,Programming for Everybody (Getting Started wit...,"This course is a ""no prerequisite"" introductio...","293,864",Self-paced on your time,The University of Michigan,Charles Severance,Introductory,Computer Science,English,English,2‚Äì4 hours per week,7 Weeks,FREE-Add a Verified Certificate for $49 USD,This course aims to teach everyone the basics ...,NaN,https://www.edx.org/course/programming-for-eve...
2,CS50's Introduction to Computer Science,An introduction to the intellectual enterprise...,"2,442,271",Self-paced on your time,Harvard University,David J. Malan-Doug Lloyd-Brian Yu,Introductory,Computer Science,English,English,6‚Äì18 hours per week,12 Weeks,FREE-Add a Verified Certificate for $90 USD,"This is CS50x , Harvard University's introduct...",NaN,https://www.edx.org/course/cs50s-introduction-...
3,The Analytics Edge,"Through inspiring examples and stories, discov...","129,555",Instructor-led on a course schedule,Massachusetts Institute of Technology,Dimitris Bertsimas-Allison O'Hair-John Silberh...,Intermediate,Data Analysis & Statistics,English,English,10‚Äì15 hours per week,13 Weeks,FREE-Add a Verified Certificate for $199 USD,"In the last decade, the amount of data availab...",NaN,https://www.edx.org/course/the-analytics-edge
4,Marketing Analytics: Marketing Measurement Str...,This course is part of a MicroMasters¬Æ Program,"81,140",Self-paced on your time,"University of California, Berkeley",Stephan Sorger,Introductory,Computer Science,English,English,5‚Äì7 hours per week,4 Weeks,FREE-Add a Verified Certificate for $249 USD,Begin your journey in a new career in marketin...,NaN,https://www.edx.org/course/marketing-analytics...

In [6]:
edx.dtypes

title                 object
summary               object
n_enrolled            object
course_type           object
institution           object
instructors           object
Level                 object
subject               object
language              object
subtitles             object
course_effort         object
course_length         object
price                 object
course_description    object
course_syllabus       object
course_url            object
dtype: object

In [7]:
coursera.head()

,name,institution,course_url,course_id
0,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,machine-learning
1,Indigenous Canada,University of Alberta,https://www.coursera.org/learn/indigenous-canada,indigenous-canada
2,The Science of Well-Being,Yale University,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being
3,Technical Support Fundamentals,Google,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals
4,Become a CBRS Certified Professional Installer...,Google - Spectrum Sharing,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training

In [8]:
coursera.dtypes

name           object
institution    object
course_url     object
course_id      object
dtype: object

In [9]:
courseraReviews.head()

,reviews,reviewers,date_reviews,rating,course_id
0,"Pretty dry, but I was able to pass with just t...",By Robert S,"Feb 12, 2020",4,google-cbrs-cpi-training
1,would be a better experience if the video and ...,By Gabriel E R,"Sep 28, 2020",4,google-cbrs-cpi-training
2,Information was perfect! The program itself wa...,By Jacob D,"Apr 08, 2020",4,google-cbrs-cpi-training
3,A few grammatical mistakes on test made me do ...,By Dale B,"Feb 24, 2020",4,google-cbrs-cpi-training
4,Excellent course and the training provided was...,By Sean G,"Jun 18, 2020",4,google-cbrs-cpi-training

In [10]:
courseraReviews.dtypes

reviews         object
reviewers       object
date_reviews    object
rating           int64
course_id       object
dtype: object

Vemos que hay columnas que no nos sirven a nuestro proposito (ejemplo: url del curso) por lo que vamos a eliminar las columnas que no nos aporten datos significativos para nuestros propositos.

In [11]:
udemy.drop(['course_id','url'],axis=1,inplace=True)
udemy.dtypes

course_title            object
is_paid                   bool
price                    int64
num_subscribers          int64
num_reviews              int64
num_lectures             int64
level                   object
content_duration       float64
published_timestamp     object
subject                 object
dtype: object

In [12]:
coursera.drop(['course_url'],axis=1,inplace=True)
coursera.dtypes

name           object
institution    object
course_id      object
dtype: object

In [13]:
edx.drop(['instructors','course_syllabus','course_url'],axis=1,inplace=True)
edx.dtypes

title                 object
summary               object
n_enrolled            object
course_type           object
institution           object
Level                 object
subject               object
language              object
subtitles             object
course_effort         object
course_length         object
price                 object
course_description    object
dtype: object

In [14]:
courseraFull=pd.merge(coursera, courseraReviews, on='course_id')

In [15]:
coursera['institution'].value_counts()

University of Pennsylvania       43
University of Michigan           31
Duke University                  24
Google Cloud                     22
IBM                              18
                                 ..
EDHEC Business School             1
INSEAD                            1
Google - Spectrum Sharing         1
New York Institute of Finance     1
UCL School of Management          1
Name: institution, Length: 134, dtype: int64

In [26]:
#courseraReviews[(courseraReviews['reviews'].str.len()<10).index]
courseraReviews.drop(courseraReviews[courseraReviews['reviews'].str.len()<10].index,inplace=True)
courseraReviews.drop(courseraReviews[courseraReviews['reviews'].isin('NaN')],axis=0,inplace=True)

In [35]:
courseraReviews[courseraReviews['rating']<2]

,reviews,reviewers,date_reviews,rating,course_id
87,This course is virtually worthless. I couldn't...,By James R,"Apr 23, 2019",1,financial-markets-global
88,This course was horrible! The Content was very...,By Sanam P,"Oct 22, 2017",1,financial-markets-global
89,Terrible lecturer. Maybe he should retire. He ...,By Brendan F,"Jan 29, 2019",1,financial-markets-global
90,This course was aweful! I feel like I didnt le...,By Eli,"Sep 18, 2017",1,financial-markets-global
91,I was expecting more from the course. It is ve...,By Sebastian S,"Jan 05, 2020",1,financial-markets-global
...,...,...,...,...,...
1454229,"Some quizzes are senseless, the course itself ...",By Mackenzie S,"Apr 24, 2020",1,computer-networking
1454230,"I did not receive my certificate, though have ...",By Shikha K S,"Jun 27, 2020",1,computer-networking
1454231,The lessons and teachings do not match up with...,By Karl P M,"Nov 05, 2019",1,computer-networking
1454232,i did'nt got my certificate and this site id v...,By ROHIT G,"Jun 09, 2020",1,computer-networking
1454233,i did'nt got my certificate and this site id v...,By ROHIT G,"Jun 09, 2020",1,computer-networking

In [27]:
courseraReviews

,reviews,reviewers,date_reviews,rating,course_id
0,"Pretty dry, but I was able to pass with just t...",By Robert S,"Feb 12, 2020",4,google-cbrs-cpi-training
1,would be a better experience if the video and ...,By Gabriel E R,"Sep 28, 2020",4,google-cbrs-cpi-training
2,Information was perfect! The program itself wa...,By Jacob D,"Apr 08, 2020",4,google-cbrs-cpi-training
3,A few grammatical mistakes on test made me do ...,By Dale B,"Feb 24, 2020",4,google-cbrs-cpi-training
4,Excellent course and the training provided was...,By Sean G,"Jun 18, 2020",4,google-cbrs-cpi-training
...,...,...,...,...,...
1454623,i liked it,By DINESH S,"Oct 02, 2020",5,computer-networking
1454669,NaN,By Christopher L J,"Sep 26, 2020",5,computer-networking
1454678,NaN,By Jerold K G,"Jun 10, 2020",5,computer-networking
1454691,NaN,By Christopher L J,"Sep 26, 2020",5,computer-networking
1454700,NaN,By Jerold K G,"Jun 10, 2020",5,computer-networking